coin/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('coinapp.urls', namespace='coinapp')),
    url(r'^collector/', include('collector.urls', namespace='collector')),
]

coinapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<title>\w+)/$', views.post_list, name='post_list'),
]

collector/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<title>\w+)/$', views.exchange, name='exchange'),
]

coinapp/models.py
from django.db import models

class Exchange(models.Model):
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    exchange = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'collector'
        ordering = ('-id',)

collector/models.py
from django.db import models

class Exchange(models.Model):
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    exchange = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'collector'
        ordering = ('-id',)

coinapp/views.py
from django.shortcuts import render
from .models import Exchange

def index(request):
    return render(request, 'coinapp/index.html')

def post_list(request, title):
    data = Exchange.objects.all()
    return render(request, 'coinapp/post_list.html', {'data': data})

collector/views.py
from django.shortcuts import render
from .exchange import upbit

def exchange(request, title):
    upbit.start()

coinapp/templates/coinapp/index.html
{% extends "coinapp/layout.html" %}

{% block content %}
    <h1>Main</h1>
{% endblock %}

coinapp/templates/coinapp/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>코인</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/v/bs4-4.0.0-beta/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-html5-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/kt-2.3.2/r-2.2.0/rg-1.0.2/rr-1.2.3/sc-1.4.3/sl-1.2.3/datatables.min.css"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Title</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'coinapp:post_list' 'item1' %}">item1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'coinapp:post_list' 'item2' %}">item2</a>
                </li>    
            </ul>
        </div>
    </nav>
    
    
    <div class="container-fluid pt-5">    
        <div class="row pt-5">
            <div class="col-sm-2 sidenav">
            
            </div>
            <div class="col-sm-8 text-conter"> 
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-sm-2 sidenav">
            
            </div>
        </div>
    </div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/v/bs4-4.0.0-beta/jszip-2.5.0/dt-1.10.16/b-1.4.2/b-colvis-1.4.2/b-html5-1.4.2/cr-1.4.1/fc-3.2.3/fh-3.1.3/kt-2.3.2/r-2.2.0/rg-1.0.2/rr-1.2.3/sc-1.4.3/sl-1.2.3/datatables.min.js"></script>
</body>
</html>

coinapp/templates/coinapp/post_list.html
{% extends "coinapp/layout.html" %}
{% block content %}
<script>
$(function () {
    $('table.data-table').DataTable({
        paging: false,
        info: false,
        dom: 'Bfrtip',
        buttons: [{
            extend:'excel',
            filename:'file_name',
            title:'title'
        }],
        language: {
            "decimal": ",",
            "thousands": "."
        }
    });
});
</script>
    <h1>{{title}}</h1>
    <table class="table table-bordered data-table">
        <thead>
            <tr>
                <th>코인명</th>
                <th>가격</th>
                <th>거래소</th>
            </tr>            
        </thead>
        <tbody>
            {% for item in data %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.exchage }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}